export { default as HeroSection } from './HeroSection.vue'
export { default as Navbar } from './NavbarComponent.vue'
export { default as PopularDestinations } from './PopularDestinations.vue'
export { default as SpecialOffer } from './SpecialOffer.vue'
export { default as OurBlog } from './OurBlog.vue'
export { default as TripPlanners } from './TripPlanners.vue'
